//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int GoalID { get; set; }
        public string GoalName { get; set; }
        public Nullable<int> RotationID { get; set; }
        public string GoalComment { get; set; }
        public string GoalFeedback { get; set; }
    
        public virtual Rotation Rotation { get; set; }
    }
}
