//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rotation()
        {
            this.Goals = new HashSet<Goal>();
        }
    
        public int RotationID { get; set; }
        public Nullable<int> GraduateID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual Graduate Graduate { get; set; }
        public virtual Project Project { get; set; }
    }
}
